spring:
  profiles:
    active: prod
  application:
    name: SWAPI-Proxy

server:
  port: 8080

cache:
  time: 1
  timeUnit: days

rate-limit:
  cacheName: rate-limit-buckets
  headerKey: X-RateLimit-Remaining
  capacity: 10000
  time: 1
  timeUnit: days

client:
  swapi:
    baseUrl: https://swapi.dev/api/
    rateLimit: 10000 # per day